language: java
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew clean 
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bush <(curl -s https://codecov.io/bash)
